INSERT INTO public.attribute_catalog (field, value, synonyms, source_sheet) VALUES
('Age', '18-24', 'young, gen z, youth', 'Demographics'),
('Age', '25-34', 'millennials, young professionals', 'Demographics'),
('Age', '35-44', 'mid career', 'Demographics'),
('Age', '45-60', 'mature, older', 'Demographics'),
('Gender', 'Female', 'women, ladies, female', 'Demographics'),
('Gender', 'Male', 'men, male', 'Demographics'),
('City', 'Mumbai', 'bombay', 'Demographics'),
('City', 'Delhi NCR', 'delhi, ncr, gurgaon, noida', 'Demographics'),
('City', 'Bengaluru', 'bangalore', 'Demographics'),
('City', 'Hyderabad', null, 'Demographics'),
('Tier', 'Metro', 'metros, tier 1 cities, urban', 'Demographics'),
('Tier', 'Tier 1', 'metro adjacent, large cities', 'Demographics'),
('Tier', 'Tier 2', 'smaller cities, emerging cities', 'Demographics'),
('Income Level', 'Premium', 'affluent, wealthy, rich, luxury, high income, HNI, premium', 'Demographics'),
('Income Level', 'High', 'upper middle class, well off', 'Demographics'),
('Income Level', 'Middle', 'mid income, middle class', 'Demographics'),
('Income Level', 'Mass', 'budget conscious, value seekers', 'Demographics'),
('Profession', 'Entrepreneurs', 'founders, business owners', 'Demographics'),
('Profession', 'Consultants', null, 'Demographics'),
('Profession', 'Finance Professionals', 'bankers, investors', 'Demographics'),
('Profession', 'Senior Corporate Executives', 'CXOs, leadership, executives', 'Demographics'),
('OTT Engagement Level', 'Heavy', 'binge watchers, power users, heavy streamers', 'OTT'),
('OTT Engagement Level', 'Medium', 'regular viewers', 'OTT'),
('OTT Engagement Level', 'Light', 'casual viewers', 'OTT'),
('Preferred OTT Platform', 'Netflix', 'netflix users', 'OTT'),
('Preferred OTT Platform', 'Prime Video', 'amazon prime', 'OTT'),
('Preferred OTT Platform', 'JioHotstar', 'hotstar, jio', 'OTT'),
('Genre Affinity', 'Drama', null, 'OTT'),
('Genre Affinity', 'Premium Series', 'prestige tv, premium shows', 'OTT'),
('Genre Affinity', 'Documentary', 'docuseries', 'OTT'),
('Genre Affinity', 'Crime Thriller', 'thrillers, crime shows', 'OTT'),
('Genre Affinity', 'Romance', 'romantic, love stories', 'OTT'),
('Device Tier', 'Premium Flagship', 'iphone pro, flagship phones, high end devices', 'Device'),
('Device Tier', 'Mid-range', 'mid range phones', 'Device'),
('Device Type', 'Smart TV', 'connected tv, CTV, television', 'Device'),
('Device Type', 'Smartphone', 'mobile, phone', 'Device'),
('Shopping Category', 'Luxury Skincare', 'luxury skincare, premium skincare, derma care, skin care, k-beauty', 'Commerce'),
('Shopping Category', 'Premium Beauty', 'beauty, premium beauty, cosmetics, makeup, premium cosmetics', 'Commerce'),
('Shopping Category', 'Fragrances', 'perfume, luxury perfume, attar', 'Commerce'),
('Shopping Category', 'Luxury Fashion', 'designer wear, luxury apparel, premium fashion', 'Commerce'),
('Shopping Category', 'Gourmet Food', 'premium food, artisanal food', 'Commerce'),
('Shopping Category', 'Electronics', 'gadgets, tech', 'Commerce'),
('Purchase Behavior', 'Luxury Buyers', 'luxury buyers, high spenders, premium purchasers', 'Commerce'),
('Purchase Behavior', 'Frequent Online Shoppers', 'online shoppers, ecommerce regulars', 'Commerce'),
('Purchase Behavior', 'Brand Conscious', 'brand loyal, brand conscious', 'Commerce'),
('Purchase Behavior', 'Deal Seekers', 'discount hunters, bargain seekers', 'Commerce'),
('Brand Affinity', 'Luxe Brands', 'Estee Lauder, Chanel, Dior, La Mer, luxury brands', 'Commerce'),
('Brand Affinity', 'D2C Beauty Brands', 'Nykaa, Sugar, Mamaearth, d2c beauty', 'Commerce'),
('Brand Affinity', 'K-Beauty Brands', 'korean beauty, kbeauty, Innisfree, Laneige', 'Commerce'),
('Household Type', 'Urban Family', 'urban households, city families', 'Demographics'),
('Household Type', 'Young Couple', 'dinks, newly married', 'Demographics'),
('Household Type', 'Single Professional', 'bachelors, living alone', 'Demographics');